# Generated by Django 3.0.3 on 2020-12-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('commentor_name', models.CharField(max_length=200)),
                ('commentor_email', models.CharField(max_length=200)),
                ('commentor_image', models.CharField(max_length=200)),
                ('comment_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('author_name', models.CharField(max_length=200)),
                ('author_email', models.CharField(max_length=200)),
                ('author_image', models.CharField(max_length=200)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=200)),
                ('voter_email', models.CharField(max_length=200)),
                ('up_vote', models.BooleanField(blank=True, default=False, null=True)),
                ('down_vote', models.BooleanField(blank=True, default=False, null=True)),
                ('up_vote_color', models.CharField(max_length=200)),
                ('down_vote_color', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
